// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "openaiKey": string;
      "openaiModel": string;
      "deepseekKey": string;
      "deepseekModel": string;
      "conversationMode": string;
      "agentTone": string;
    };
  }
}
